//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerId { get; set; }
        public string customerNo { get; set; }
        public string companyName { get; set; }
        public string contacts { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public string telPhone { get; set; }
        public string tax { get; set; }
        public string discount { get; set; }
        public string InvoiceMethod { get; set; }
        public string backMethod { get; set; }
        public Nullable<int> isFanben { get; set; }
        public string companyAddress { get; set; }
        public string otherDangAn { get; set; }
        public string modifyPriceRecord { get; set; }
        public string description { get; set; }
        public Nullable<int> isShowPrice { get; set; }
        public Nullable<int> islock { get; set; }
        public string zhangHao { get; set; }
        public string shuiHao { get; set; }
        public Nullable<int> isAddInfo { get; set; }
    }
}
