//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proOrders
    {
        public int orderId { get; set; }
        public string orderNum { get; set; }
        public string customNum { get; set; }
        public string heTongNum { get; set; }
        public string customOrderNum { get; set; }
        public string customWLBH { get; set; }
        public string customManager { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> editTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<decimal> yikaipiaoMoney { get; set; }
        public Nullable<decimal> yijiekuanMoney { get; set; }
        public string faPiaoDanhao { get; set; }
        public string chengShuiHao { get; set; }
        public string Remark1 { get; set; }
        public Nullable<int> editUser { get; set; }
        public Nullable<int> isTiXing { get; set; }
        public string shuRuXianchang { get; set; }
        public string shuChuXianchang { get; set; }
        public string 发货状态 { get; set; }
    }
}
