//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class proOrdersDetail
    {
        public int orderDetailId { get; set; }
        public string orderNum { get; set; }
        public string proType { get; set; }
        public Nullable<int> proNum { get; set; }
        public Nullable<decimal> ProPrice { get; set; }
        public string withWorkNo { get; set; }
        public Nullable<System.DateTime> printTime { get; set; }
        public string printType { get; set; }
        public Nullable<int> printCount { get; set; }
        public string piHao { get; set; }
        public Nullable<System.DateTime> planSendTime { get; set; }
        public string productAddress { get; set; }
        public Nullable<System.DateTime> printSGDTime { get; set; }
        public Nullable<int> printSGDCount { get; set; }
        public Nullable<System.DateTime> printSGDJLTime { get; set; }
        public Nullable<int> printSGDJLCount { get; set; }
        public Nullable<System.DateTime> printQLDTime { get; set; }
        public Nullable<int> printQLDCount { get; set; }
        public Nullable<System.DateTime> printCCJYBGTime { get; set; }
        public Nullable<int> printCCJYBGCount { get; set; }
        public Nullable<System.DateTime> printSHDTime { get; set; }
        public Nullable<int> printSHDCount { get; set; }
        public Nullable<System.DateTime> printBZBQTime { get; set; }
        public Nullable<int> printBZBQCount { get; set; }
        public Nullable<System.DateTime> printZYSXTime { get; set; }
        public Nullable<int> printZYSXCount { get; set; }
        public Nullable<System.DateTime> printYYQRDTime { get; set; }
        public Nullable<int> printYYQRDCount { get; set; }
        public Nullable<int> sGDCount { get; set; }
        public string 发货状态 { get; set; }
    }
}
