//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_Material
    {
        public int ID { get; set; }
        public string MaterialName { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UpperLimit { get; set; }
        public Nullable<int> LowerLimit { get; set; }
        public string TechnicalParameter { get; set; }
        public Nullable<int> Status { get; set; }
        public string WareHouseIDs { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }
}
