//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_Suppliers
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string ContactMan { get; set; }
        public string Telephone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Position { get; set; }
        public string AssessmentLevel { get; set; }
        public string InvoiceFa { get; set; }
        public string Payment { get; set; }
        public Nullable<int> IsContractModel { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
        public string TaxpayerNumber { get; set; }
        public string CompanyAdress { get; set; }
        public string OtherContactMan { get; set; }
        public string ContactManDetailInfo { get; set; }
        public Nullable<int> LoginUserID { get; set; }
        public Nullable<int> Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }
}
