//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_Log
    {
        public int ID { get; set; }
        public Nullable<int> DoID { get; set; }
        public Nullable<int> DoType { get; set; }
        public string DoContent { get; set; }
        public string DoBy { get; set; }
        public Nullable<System.DateTime> DoTime { get; set; }
    }
}
