//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_OutWareHouseLog
    {
        public int ID { get; set; }
        public string OutNo { get; set; }
        public string MaterialName { get; set; }
        public string ModelNumber { get; set; }
        public string CategoryName { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> Amout { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public string WareHouseName { get; set; }
        public string Remark { get; set; }
        public string DealWithBy { get; set; }
        public string Department { get; set; }
        public string DoBy { get; set; }
        public Nullable<System.DateTime> DoTime { get; set; }
    }
}
