//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_PurchaseContractItem
    {
        public int ID { get; set; }
        public string ContractID { get; set; }
        public string OrderID { get; set; }
        public string MaterialName { get; set; }
        public string ModelNumber { get; set; }
        public string CategoryName { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> Amout { get; set; }
        public string TechnicalParameters { get; set; }
        public string Requirement { get; set; }
    }
}
