//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string productNum { get; set; }
        public Nullable<int> waiBZ { get; set; }
        public string NeiBZ { get; set; }
        public string NeiBZDW { get; set; }
        public string bian { get; set; }
        public string jingDu { get; set; }
        public string xianXingdu { get; set; }
        public string eDingJC { get; set; }
        public Nullable<int> tieXiCount { get; set; }
        public string guiGe { get; set; }
        public string caiLiao { get; set; }
        public string xingNeng { get; set; }
        public string chuLiMethod { get; set; }
        public string baoHeDian { get; set; }
        public Nullable<int> xianQuanCount { get; set; }
        public string chujZaShu { get; set; }
        public string chujXianJing { get; set; }
        public string chujRaoXianZD { get; set; }
        public string chujXianTouCD { get; set; }
        public string chujXiantouCL { get; set; }
        public string chujTongMD { get; set; }
        public string cijZaShu { get; set; }
        public string cijXianJing { get; set; }
        public string cijRaoXianZD { get; set; }
        public string cijXianTouCD { get; set; }
        public string cijXianTouCL { get; set; }
        public string cijTongMD { get; set; }
        public string xqjcyqEquip { get; set; }
        public string xqjcyqShuRuState { get; set; }
        public string xqjcyqShuChuState { get; set; }
        public string xqjcyqJiaoCha { get; set; }
        public string xqjcyqFuZai { get; set; }
        public string biaoShiNo { get; set; }
        public string waiKeNo { get; set; }
        public Nullable<int> waiKeCount { get; set; }
        public string yongJiaoCS { get; set; }
        public string shuRu { get; set; }
        public string shuChu { get; set; }
        public string biaoShiAddress { get; set; }
        public string chajianNo { get; set; }
        public Nullable<int> chajianCount { get; set; }
        public string waiXingTZ { get; set; }
        public string cpjccsEquip { get; set; }
        public string cpjccsShuRuState { get; set; }
        public string cpjccsShuChuState { get; set; }
        public string CpjccsJiaoChaBH { get; set; }
        public string cpjccsFuZai { get; set; }
        public string cpjccsNaiYa { get; set; }
        public string cpjccsTongMD { get; set; }
        public string guanJiaoZhenLX { get; set; }
        public Nullable<int> guanJIaoZhenLXCount { get; set; }
        public string guanJiaoZhenLXTOW { get; set; }
        public Nullable<int> guanJiaoZhenLXTOWCount { get; set; }
        public string shuRuXC { get; set; }
        public string shuChuXC { get; set; }
        public string peiXianSR { get; set; }
        public Nullable<decimal> peiXianSRCount { get; set; }
        public string peiXianSC { get; set; }
        public Nullable<decimal> peiXianSCCount { get; set; }
        public string remark { get; set; }
        public Nullable<int> isModifyTZ { get; set; }
        public string biaoShiPicture { get; set; }
        public Nullable<int> isModifyWaikeNo { get; set; }
        public string gongyiZYSX { get; set; }
        public string baoZhuangHeGG { get; set; }
        public string baoZhuangXiangGG { get; set; }
        public string baoHeDianTestTJ { get; set; }
        public string guJia { get; set; }
        public string tongPai { get; set; }
        public string ciHuan { get; set; }
        public string duanZi { get; set; }
        public string xianLuBan { get; set; }
        public string jiaoPian { get; set; }
        public string pingBi { get; set; }
        public string wenYaGuan { get; set; }
        public string dianZu { get; set; }
        public string luoSi { get; set; }
        public string reSuoTaoGuan { get; set; }
        public string anZhuangPJ { get; set; }
        public string yuanQiJian1 { get; set; }
        public string yuanQiJian2 { get; set; }
        public string yuanQiJian3 { get; set; }
        public string yuanQiJian4 { get; set; }
        public string gujiaCanshu { get; set; }
        public Nullable<int> gujiaCount { get; set; }
        public string tongpaiCanshu { get; set; }
        public Nullable<int> tongpaoCount { get; set; }
        public string cihuanCanshu { get; set; }
        public Nullable<int> cihuanCount { get; set; }
        public string duanziCanshu { get; set; }
        public Nullable<int> duanziCount { get; set; }
        public string xianlubanCanshu { get; set; }
        public Nullable<int> xianlubanCount { get; set; }
        public string jiaopianCanshu { get; set; }
        public Nullable<int> jiaopianCount { get; set; }
        public string pingbiCanshu { get; set; }
        public Nullable<int> pingbiCount { get; set; }
        public string wenyaguanCanshu { get; set; }
        public Nullable<int> wenyaguanCount { get; set; }
        public string dianzuCanshu { get; set; }
        public Nullable<int> dianzuCount { get; set; }
        public string luosiCanshu { get; set; }
        public Nullable<int> luosiCount { get; set; }
        public string resuotaoguanCanshu { get; set; }
        public Nullable<int> resuotaoguanCount { get; set; }
        public string anzhuangPJCanshu { get; set; }
        public Nullable<int> anzhuangPJCount { get; set; }
        public string yuanqijian1Canshu { get; set; }
        public Nullable<int> Yuanqijian1Count { get; set; }
        public string Yuanqijian2Canshu { get; set; }
        public Nullable<int> Yuanqijian2Count { get; set; }
        public string Yuanqijian3Canshu { get; set; }
        public Nullable<int> Yuanqijian3Count { get; set; }
        public string Yuanqijian4Canshu { get; set; }
        public Nullable<int> Yuanqijian4Count { get; set; }
    }
}
