//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_NoWanChengOrder
    {
        public int orderDetailId { get; set; }
        public string orderNum { get; set; }
        public string proType { get; set; }
        public Nullable<int> proNum { get; set; }
        public Nullable<int> printSHDCount { get; set; }
        public Nullable<System.DateTime> planSendTime { get; set; }
        public string remark { get; set; }
        public string companyName { get; set; }
        public string customerNo { get; set; }
        public Nullable<int> SendCount { get; set; }
    }
}
