//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaiKeImg
    {
        public int imgId { get; set; }
        public string waiKeNo { get; set; }
        public string waiKeImg1 { get; set; }
        public Nullable<int> isModify { get; set; }
    }
}
