//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPrintWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendDetail
    {
        public int sendId { get; set; }
        public string orderNum { get; set; }
        public string proType { get; set; }
        public Nullable<int> sendProNum { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public string packingDetail { get; set; }
        public Nullable<int> packingCount { get; set; }
        public string packingCompanyName { get; set; }
        public string sendNum { get; set; }
        public string remark { get; set; }
        public string suiGongDanNum { get; set; }
    }
}
